### ISSUE TITLE
Package.json not in root of the workspace support

### ISSUE THREAD

**Issue by lllopo** [sketchbuch/vsc-packages#102]
There are projects, where package.json is not in the root of the workspace. This is fully supported by VS Code core functions, so I guess it would be easy to follow the same path and implement it for this extension too.

**Comment by sketchbuch** [comment]
Hi, do you mean yarn workpaces?

https://classic.yarnpkg.com/en/docs/workspaces/

Support for this is planned, I have a ticket already: https://github.com/sketchbuch/vsc-packages/issues/36

Or do you mean some other structure? Can you make a diagram maybe of what your structure looks like?

**Comment by lllopo** [comment]
Hi, 
no, I mean the physical location of the package.json file. For example I have a project that is PHP in nature, and the css/js assets are in a subfolder like this :

Project1
|-- some folder
|-- some folder
|-- assets
.......|-- dist
.......|-- src
..............|-- js
..............|-- css
.. etc ...

now, the root of the VS Code workspace is the Project 1 folder, BUT my package.json is located in the assets/src subfolder and this is actually the root of the npm and webpack part of it. This is properly detected and handled by VS Code itself, so it finds and runs the scripts and everything, but your plugin does not detect the package.json at all.

**Comment by sketchbuch** [comment]
My plugin only looks at the worksapce folders and doesn't dive any deeper. I will try and add this when I add support for yarn workspaces

**Comment by lllopo** [comment]
ok, thanks. Maybe you should just take a look how VS Code does this ... or maybe even use VS Code own detection results, if possible. Would be a very streamlined approach, but don't know if technically possible.

**Comment by sketchbuch** [comment]
This issue is now fixed and will be in the next release

**Comment by sketchbuch** [comment]
Release is out now (v1.5.1) - supports yarn workspaces. Optionaly supports looking for package.json files from 1-5 levels deep below each worksapce folder (not yarn workspace folder). This is off by default, to change adjust the settings for the extension and specify a depth value (from 1-5).
