### ISSUE TITLE
VSCode Insiders - Not listing packages

### ISSUE THREAD

**Issue by sannamalai176** [sketchbuch/vsc-packages#91]
Not working with VS Code Insiders.

**Comment by sketchbuch** [comment]
I think the API has changed, I was storing data in the application context - objects, and it now doesn't seem to work. I shall update this ticket when I have fixed it. It also seems broken with the current stable release.

**Comment by sketchbuch** [comment]
Fixed in version 1.2.2

**Comment by sketchbuch** [comment]
https://github.com/sketchbuch/vsc-packages/pull/93
